name: Deploy to Develop Server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
      image: ${{ steps.build-image.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_ACCESS_SECRET }}
          aws-region: ap-northeast-2
          mask-aws-account-id: no

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Backend Amazon ECR
        id: build-be-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_BE_REPOSITORY: resume
        run: |
          GITHUB_SHA=${{ github.sha }}
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t $ECR_REGISTRY/$ECR_BE_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_BE_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_BE_REPOSITORY:$IMAGE_TAG"

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout Kusomize Repository
        uses: actions/checkout@v2
        with:
          repository: chungjung-d/chungjung-kubernetes
          ref: master

          token: ${{ secrets.ACTION_TOKEN }}
          path: chungjung-kubernetes

      - name: Update Kubernetes resources
        run: |
          cd chungjung-kubernetes/profile/overlays/production/
          kustomize edit set image $ECR_REGISTRY/$ECR_BE_REPOSITORY:$IMAGE_TAG
          cat kustomization.yaml

      - name: Commit and push changes
        run: |
          cd chungjung-kubernetes
          git config --global user.email "chungjung.d@gmail.com"
          git config --global user.name "argocd"
          git add .
          git commit -m "Update image $IMAGE_TAG"
          git push origin master